In [1]:
from pyspark.sql import SparkSession
import pandas as pd

In [2]:
spark = SparkSession.builder.appName('dates').getOrCreate()

In [3]:
df = spark.read.csv('/FileStore/tables/0.csv',inferSchema=True,header=True)

In [4]:
df.printSchema

In [5]:

df.head()

In [6]:
from pyspark.sql.functions import dayofmonth as dom, dayofyear as doy, weekofyear as woy, date_format as dat_form

In [7]:
df.select(df['birthDate']).show()

In [8]:
df.select(dom(df['birthDate'])).show()

In [9]:
from pyspark.sql.functions import month, year

In [10]:
df.select(year(df['birthDate'])).show()

In [11]:
from pyspark.sql.functions import year, hour, minute, format_number

In [12]:
df.select(hour(df['commitTimestamp'])).show()

In [13]:
df.select(minute(df['commitTimestamp'])).show()

In [14]:
new_df = df.withColumn("Year",year(df['commitTimestamp']))

In [15]:
result = new_df.groupBy('Year').mean()['avg(Year)','avg(age)']

In [16]:
result = result.withColumnRenamed('avg(Year)','Year')

In [17]:
result = result.select('Year',format_number('avg(age)',2).alias("Mean Age")).show()